/* ---------- Chatynkowo — fairytale map & cottage loader ---------- */
(() => {
  'use strict';

  const COTTAGES_URL = 'data/cottages.json';
  const CODE_HASHES_URL = 'data/code_hashes.json';
  const ROUTE_URL    = 'dist/route.json';   // generated by scripts/build.sh
  const MD_DIR       = 'cottages';
  const AUDIO_DIR    = 'assets/stories';

  // Persistent state (localStorage I/O + badge registry) lives in
  // app_logic.js and is exposed on window.chatynkowo. Loaded with `defer`
  // before this file in index.html, so it's ready by the time we run.
  // route_logic.js (also `defer`, loaded before us) adds window.chatynkowo.route.
  const { persist, BADGES, route } = window.chatynkowo;

  const state = {
    cottages: [],
    codeHashes: null,   // { salt, entries: { sha256(salt:code) → slug } }
    route: null,   // dist/route.json once loaded (null until built/loaded)
  };

  /* ---------- Load cottages ---------- */
  async function loadCottages() {
    const res = await fetch(COTTAGES_URL);
    state.cottages = await res.json();
    await loadTitles();
  }

  /* Each cottage's title lives ONLY in its .md frontmatter — the single
     source of truth for all text; data/cottages.json carries just
     location/map data. Fetched in parallel at startup: the files are tiny,
     and the dialogs hit the same HTTP cache when they re-fetch them later. */
  async function loadTitles() {
    await Promise.all(state.cottages.map(async (c) => {
      try {
        const res = await fetch(`${MD_DIR}/${c.slug}.md`);
        const fm = (await res.text()).match(/^---\n([\s\S]*?)\n---/);
        const t = fm && fm[1].match(/^title:\s*("?)(.*?)\1\s*$/m);
        c.title = (t && t[2]) || c.slug;
      } catch (_) { c.title = c.slug; }
    }));
  }

  /* The plaque codes are SECRET — they live only in private/codes.json, which
     never reaches the published site. The page validates an entered code by
     comparing its salted SHA-256 against this generated lookup
     (private/build-code-hashes.mjs), so the plaintext codes cannot be read
     off the site. A failed load only disables code entry, never the map. */
  async function loadCodeHashes() {
    try {
      const res = await fetch(CODE_HASHES_URL);
      if (res.ok) state.codeHashes = await res.json();
    } catch (_) { /* offline / missing file — handled at submit time */ }
  }

  async function sha256Hex(text) {
    const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text));
    return Array.from(new Uint8Array(buf), b => b.toString(16).padStart(2, '0')).join('');
  }

  /* Returns the cottage matching a plaque code, or null. */
  async function cottageByCode(code) {
    if (!state.codeHashes) return null;
    const hash = await sha256Hex(`${state.codeHashes.salt}:${code}`);
    const slug = state.codeHashes.entries[hash];
    return slug ? state.cottages.find(c => c.slug === slug) || null : null;
  }

  /* ---------- Load the pre-built tourist route ----------
     dist/route.json is produced by scripts/build.sh from the cottage
     locations. There is intentionally NO client-side fallback: if the build
     hasn't run, renderRoute() shows a "build the app first" message so local
     dev and the deployed site behave the same way. */
  async function loadRoute() {
    try {
      const res = await fetch(ROUTE_URL, { cache: 'no-cache' });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      state.route = await res.json();
    } catch (_) {
      state.route = null;
    }
  }

  /* ---------- Cottage hotspots (image overlay) ----------
     The background is the PIN-LESS base map (assets/img/map_base_vertical.webp).
     Every pin on the map is drawn here, from data: for each cottage we place a
     <button> at its mapX/mapY position (a PERCENTAGE of the image in
     data/cottages.json), styled as a visible pin via CSS (.cottage-hotspot →
     map-pin.svg, blue map-pin-found.svg once found). This overlay is the SINGLE
     source of pins — never bake pins into the base image, or they become "dead
     pins" with no cottage behind them. CSS gives each pin a gold pulsing glow
     on hover/focus and an animated zoom on click. */
  const ZOOM_DELAY_MS = 360;  // matches the .is-clicked CSS transition

  function makeHotspot(c, onActivate) {
    const x = Number(c.mapX);
    const y = Number(c.mapY);
    if (!Number.isFinite(x) || !Number.isFinite(y)) return null;
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'cottage-hotspot';
    if (persist.isFound(c.slug)) btn.classList.add('cottage-hotspot--found');
    btn.dataset.slug  = c.slug;
    btn.dataset.label = c.title;
    const stateLabel = persist.isFound(c.slug) ? ' (odkryta)' : '';
    btn.setAttribute(
      'aria-label',
      `${c.title}${stateLabel}. Kliknij, aby otworzyć opis i nawigację.`
    );
    btn.style.left = x + '%';
    btn.style.top  = y + '%';
    btn.addEventListener('click', (e) => {
      // Don't let the click bubble up to the map-stage / map-zoom handlers.
      e.stopPropagation();
      onActivate(btn, c);
    });
    return btn;
  }

  function drawCottages() {
    const host = document.getElementById('mapHotspots');
    if (!host) return;
    host.innerHTML = '';

    const modal = document.getElementById('pinModal');

    state.cottages.forEach((c) => {
      const btn = makeHotspot(c, (el, cot) => {
        el.classList.add('is-clicked');
        setTimeout(() => {
          openPinInfo(cot);
          const reset = () => {
            el.classList.remove('is-clicked');
            if (modal) modal.removeEventListener('close', reset);
          };
          if (modal) modal.addEventListener('close', reset);
        }, ZOOM_DELAY_MS);
      });
      if (btn) host.appendChild(btn);
    });

    drawZoomHotspots();
  }

  /* Zoom-mode hotspots: same positions, but click goes straight to the
     pin-info dialog — the map is already large, no extra zoom animation. */
  function drawZoomHotspots() {
    const host = document.getElementById('mapZoomHotspots');
    if (!host) return;
    host.innerHTML = '';
    state.cottages.forEach((c) => {
      const btn = makeHotspot(c, (_el, cot) => openPinInfo(cot));
      if (btn) host.appendChild(btn);
    });
  }

  /* ---------- Tourist-route panel ----------
     Renders the summary, the per-stage Google Maps / Mapy.cz links and the
     GPX download from dist/route.json. When the build hasn't run (state.route
     is null) it shows a clear "build the app first" message instead. */
  function plEtap(n) {
    if (n === 1) return 'etap';
    const t = n % 10, h = n % 100;
    return (t >= 2 && t <= 4 && (h < 10 || h >= 20)) ? 'etapy' : 'etapów';
  }

  function renderRoute() {
    const panel   = document.getElementById('routePanel');
    const summary = document.getElementById('routeSummary');
    const stagesEl = document.getElementById('routeStages');
    const gpx     = document.getElementById('routeGpx');
    if (!panel || !summary || !stagesEl) return;

    panel.removeAttribute('hidden');

    if (!state.route) {
      summary.textContent = '';
      stagesEl.innerHTML =
        `<p class="route-error">⚠ Brakuje pliku <code>${ROUTE_URL}</code> —
         najpierw zbuduj aplikację: <code>npm run build</code>
         (lub <code>scripts/build.sh</code>), a trasa pojawi się tutaj.</p>`;
      if (gpx) gpx.setAttribute('hidden', '');
      return;
    }

    const r = state.route;
    const multi = r.stages.length > 1;
    summary.textContent =
      `${r.stopCount} chatynek · ~${r.distanceKm} km · ` +
      `${r.stages.length} ${plEtap(r.stages.length)}`;

    stagesEl.innerHTML = '';
    r.stages.forEach((s) => {
      const row = document.createElement('div');
      row.className = 'route-stage';

      const label = document.createElement('div');
      label.className = 'route-stage__label';
      label.textContent = multi
        ? `Etap ${s.index} · ${s.count} chatynek`
        : `Cała trasa · ${s.count} chatynek`;

      const links = document.createElement('div');
      links.className = 'route-stage__links';
      for (const [text, href] of [['Google Maps', s.google], ['Mapy.cz', s.mapy]]) {
        const a = document.createElement('a');
        a.className = 'btn btn--ghost route-stage__link';
        a.href = href;
        a.target = '_blank';
        a.rel = 'noopener';
        a.textContent = text;
        links.appendChild(a);
      }

      row.appendChild(label);
      row.appendChild(links);
      stagesEl.appendChild(row);
    });

    if (gpx && r.gpxPath) {
      gpx.href = r.gpxPath;
      gpx.setAttribute('download', '');
      gpx.removeAttribute('hidden');
    } else if (gpx) {
      gpx.setAttribute('hidden', '');
    }
  }

  function showDialog(modal) {
    if (typeof modal.showModal === 'function') modal.showModal();
    else modal.setAttribute('open', '');
  }
  function closeDialog(modal) {
    if (typeof modal.close === 'function') modal.close();
    else modal.removeAttribute('open');
  }

  /* The PIN dialog shows how to get there + what to do once you arrive;
     everything else stays in the STORY dialog. The "Jak znaleźć Chatynkę"
     link list is no longer rendered from markdown — the pin dialog builds
     its own nav block from the authoritative cottages.json coordinates
     (see navBlockHtml) — but it's still excluded here so it never leaks
     into the story body. */
  const LOCATION_SECTION = 'Jak znaleźć Chatynkę';
  const ARRIVAL_SECTION  = 'Co zrobić, gdy trafisz pod chatynkę?';
  const PIN_SECTIONS = [LOCATION_SECTION, ARRIVAL_SECTION];
  /* The only markdown section the pin dialog still renders verbatim. */
  const TODO_SECTIONS = [ARRIVAL_SECTION];

  async function fetchCottageMd(slug) {
    const res = await fetch(`${MD_DIR}/${slug}.md`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const raw = await res.text();
    return raw.replace(/^---[\s\S]*?---\s*/, '');  // strip YAML frontmatter
  }

  /* Split markdown by `## …` headings into { intro, sections: [{title, body}] }
     where intro is everything before the first h2. */
  function splitMd(raw) {
    const lines = raw.split('\n');
    let intro = [];
    const sections = [];
    let cur = null;
    for (const line of lines) {
      const m = line.match(/^##\s+(.+?)\s*$/);
      if (m) {
        if (cur) sections.push(cur);
        cur = { title: m[1], lines: [] };
      } else if (cur) {
        cur.lines.push(line);
      } else {
        intro.push(line);
      }
    }
    if (cur) sections.push(cur);
    return {
      intro: intro.join('\n').trim(),
      sections: sections.map(s => ({ title: s.title, body: s.lines.join('\n').trim() })),
    };
  }

  function renderSections(sections, includeTitles) {
    const include = new Set(includeTitles);
    return sections
      .filter(s => include.has(s.title))
      .map(s => `## ${s.title}\n\n${s.body}`)
      .join('\n\n');
  }
  function renderStoryMd(parts) {
    const exclude = new Set(PIN_SECTIONS);
    const rest = parts.sections
      .filter(s => !exclude.has(s.title))
      .map(s => `## ${s.title}\n\n${s.body}`)
      .join('\n\n');
    return [parts.intro, rest].filter(Boolean).join('\n\n');
  }
  function mdToHtml(md) {
    return window.marked ? window.marked.parse(md) : escapeHtml(md);
  }

  /* Renders a small badge under the title in the pin dialog reflecting
     whether this cottage has already been uncovered. Driven by exactly
     the same persist.isFound(slug) check that paints the pin blue, so
     the two indicators can never disagree. */
  function pinStatusHtml(slug) {
    if (persist.isFound(slug)) {
      const entry = persist.data.found[slug] || {};
      let when = '';
      if (entry.foundAt) {
        try {
          when = new Date(entry.foundAt)
            .toLocaleDateString('pl-PL', { dateStyle: 'long' });
        } catch (_) { /* fall back to no date */ }
      }
      return `<p class="pin-status pin-status--found">
                <span class="pin-status__check" aria-hidden="true">✓</span>
                Chatynka odkryta${when
                  ? ` <span class="pin-status__sep">·</span> <time datetime="${entry.foundAt}">${when}</time>`
                  : ''}
              </p>`;
    }
    return `<p class="pin-status pin-status--unfound">
              Jeszcze nie odkryta — znajdź ją w lesie i wpisz tajny kod z&nbsp;tabliczki.
            </p>`;
  }

  /* Navigation block for the pin dialog, built from the cottage's
     authoritative cottages.json coordinates (NOT the markdown, whose links
     were hand-written and sometimes disagree with the data). Always offers
     Google Maps and Mapy.cz. */
  function navBlockHtml(c) {
    const lat = Number(c.lat), lng = Number(c.lng);
    if (!route || !Number.isFinite(lat) || !Number.isFinite(lng)) return '';
    const coord = `${lat}, ${lng}`;
    return `
      <h2>Jak tu dotrzeć</h2>
      <p class="pin-nav__coord"><strong>Współrzędne:</strong> <code>${coord}</code></p>
      <p class="pin-nav">
        <a class="btn btn--ghost pin-nav__link" target="_blank" rel="noopener"
           href="${route.googlePointUrl(c)}">Google Maps</a>
        <a class="btn btn--ghost pin-nav__link" target="_blank" rel="noopener"
           href="${route.mapyPointUrl(c)}">Mapy.cz</a>
      </p>`;
  }

  /* ---------- Pin-click dialog ----------
     Shown when the user clicks a pin on either the inline map or the
     fullscreen zoomed map. Shows a generated "Jak tu dotrzeć" nav block
     (coords + map links) plus the "Co zrobić…" markdown section — the rest
     (story body + audio) is the reward for finding it and entering the code. */
  async function openPinInfo(c) {
    const modal   = document.getElementById('pinModal');
    const content = document.getElementById('pinContent');
    const title   = document.getElementById('pinTitle');
    if (!modal || !content) return;
    title.textContent = c.title;
    // Mirror the pin's "found" flag on the dialog itself so future styling
    // hooks (border, header tint, ...) can react to discovery state.
    modal.classList.toggle('modal--found', persist.isFound(c.slug));
    const status = pinStatusHtml(c.slug);
    const nav    = navBlockHtml(c);
    content.replaceChildren(title, document.createRange().createContextualFragment(
      status + nav + '<p><em>Ładuję wskazówki…</em></p>'));
    showDialog(modal);
    try {
      const parts = splitMd(await fetchCottageMd(c.slug));
      const md    = renderSections(parts.sections, TODO_SECTIONS);
      content.replaceChildren(title, document.createRange().createContextualFragment(
        status + nav + mdToHtml(md)));
    } catch (err) {
      content.replaceChildren(title, document.createRange().createContextualFragment(
        status + nav + '<p>Nie udało się wczytać wskazówek do tej Chatynki.</p>'));
    }
  }

  /* ---------- Neighbouring cottages (story dialog) ----------
     Picks the `n` nearest cottages to `c`, preferring ones the visitor
     hasn't found yet (to nudge further exploration). If fewer than `n`
     undiscovered cottages remain nearby, tops up with the nearest already-
     found ones (rendered with a ✓). Distance via the shared haversine. */
  function pickNeighbors(c, n) {
    const lat = Number(c.lat), lng = Number(c.lng);
    if (!route || !Number.isFinite(lat) || !Number.isFinite(lng)) return [];
    const here = { lat, lng };
    const ranked = state.cottages
      .filter((x) => x.slug !== c.slug &&
                     Number.isFinite(Number(x.lat)) && Number.isFinite(Number(x.lng)))
      .map((x) => ({
        c: x,
        km: route.haversineKm(here, { lat: Number(x.lat), lng: Number(x.lng) }),
        found: persist.isFound(x.slug),
      }))
      .sort((a, b) => a.km - b.km);

    const picks = ranked.filter((o) => !o.found).slice(0, n);
    if (picks.length < n) {
      const have = new Set(picks.map((p) => p.c.slug));
      for (const o of ranked) {
        if (picks.length >= n) break;
        if (!have.has(o.c.slug)) picks.push(o);
      }
    }
    return picks;
  }

  function fmtKm(km) {
    return km < 1 ? `${Math.round(km * 1000)} m` : `${km.toFixed(1)} km`;
  }

  /* Builds the "Stąd blisko do…" block and appends it to the story content.
     Each neighbour is a button that closes the story and opens that cottage's
     pin window (with its nav links). */
  function appendNeighbors(c) {
    const content = document.getElementById('storyContent');
    if (!content) return;
    const picks = pickNeighbors(c, 2);
    if (!picks.length) return;

    const aside = document.createElement('aside');
    aside.className = 'neighbors';

    const h = document.createElement('h2');
    h.textContent = 'Stąd blisko do…';
    aside.appendChild(h);

    const intro = document.createElement('p');
    intro.className = 'neighbors__intro';
    intro.textContent = picks.every((p) => p.found)
      ? 'W pobliżu znajdują się także te (już odkryte) chatynki:'
      : 'Skoro już tu jesteś, niedaleko czekają kolejne chatynki do odkrycia:';
    aside.appendChild(intro);

    const ul = document.createElement('ul');
    ul.className = 'neighbors__list';
    for (const p of picks) {
      const li = document.createElement('li');
      const btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'neighbors__item' + (p.found ? ' neighbors__item--found' : '');

      const name = document.createElement('span');
      name.className = 'neighbors__name';
      name.textContent = p.c.title;

      const meta = document.createElement('span');
      meta.className = 'neighbors__meta';
      meta.textContent = p.found ? `${fmtKm(p.km)} · ✓ odkryta` : `${fmtKm(p.km)} · do odkrycia`;

      btn.appendChild(name);
      btn.appendChild(meta);
      btn.addEventListener('click', () => {
        closeDialog(document.getElementById('storyModal'));
        openPinInfo(p.c);
      });
      li.appendChild(btn);
      ul.appendChild(li);
    }
    aside.appendChild(ul);
    content.appendChild(aside);
  }

  /* ---------- Story dialog (after entering a valid code) ----------
     Shows the full markdown story (without the "how to find" sections) +
     the gramophone audio player + a few neighbouring cottages. NO map
     navigation block — the user has already found this cottage. */
  async function openStory(c) {
    const modal   = document.getElementById('storyModal');
    const content = document.getElementById('storyContent');
    if (!modal || !content) return;

    content.innerHTML = '<p><em>Ładuję opowieść…</em></p>';
    loadCottageAudio(c.slug);

    showDialog(modal);

    try {
      const parts = splitMd(await fetchCottageMd(c.slug));
      content.innerHTML = mdToHtml(renderStoryMd(parts));
    } catch (err) {
      content.innerHTML = `<p>Nie udało się wczytać opowieści.</p>`;
    }
    appendNeighbors(c);
  }

  /* ---------- Audio (gramophone) ---------- */
  function fmtTime(s) {
    if (!Number.isFinite(s) || s < 0) return '0:00';
    const m = Math.floor(s / 60);
    const ss = Math.floor(s % 60).toString().padStart(2, '0');
    return `${m}:${ss}`;
  }

  function loadCottageAudio(slug) {
    const audio  = document.getElementById('audioElement');
    const player = document.getElementById('audioPlayer');
    const seek   = document.getElementById('audioSeek');
    const cur    = document.getElementById('audioCurrent');
    const dur    = document.getElementById('audioDuration');
    if (!audio || !player) return;

    // Reset previous state.
    audio.pause();
    audio.removeAttribute('src');
    audio.load();
    player.classList.remove('is-playing');
    player.setAttribute('hidden', '');
    seek.value = 0;
    cur.textContent = '0:00';
    dur.textContent = '0:00';

    // Reveal the player only once we know the file is loadable.
    audio.preload = 'metadata';
    audio.src = `${AUDIO_DIR}/${slug}.mp3`;
    audio.load();
  }

  function wireAudioPlayer() {
    const audio  = document.getElementById('audioElement');
    const player = document.getElementById('audioPlayer');
    const playBtn = document.getElementById('audioPlay');
    const seek   = document.getElementById('audioSeek');
    const cur    = document.getElementById('audioCurrent');
    const dur    = document.getElementById('audioDuration');
    if (!audio || !player) return;

    playBtn.addEventListener('click', () => {
      if (audio.paused) audio.play().catch(() => {});
      else audio.pause();
    });
    audio.addEventListener('play',  () => player.classList.add('is-playing'));
    audio.addEventListener('pause', () => player.classList.remove('is-playing'));
    audio.addEventListener('ended', () => player.classList.remove('is-playing'));

    audio.addEventListener('loadedmetadata', () => {
      player.removeAttribute('hidden');
      dur.textContent = fmtTime(audio.duration);
    });
    audio.addEventListener('error', () => {
      // No mp3 for this cottage — keep the player hidden.
      player.setAttribute('hidden', '');
    });

    audio.addEventListener('timeupdate', () => {
      cur.textContent = fmtTime(audio.currentTime);
      if (audio.duration > 0) {
        seek.value = (audio.currentTime / audio.duration) * 1000;
      }
    });

    let scrubbing = false;
    seek.addEventListener('input', () => { scrubbing = true; });
    seek.addEventListener('change', () => {
      if (audio.duration > 0) {
        audio.currentTime = (seek.value / 1000) * audio.duration;
      }
      scrubbing = false;
    });

    // Pause when the story dialog closes so audio doesn't keep playing in
    // the background after the user dismisses it.
    const story = document.getElementById('storyModal');
    if (story) story.addEventListener('close', () => audio.pause());
  }

  function escapeHtml(s) {
    return s.replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  }

  function wireDialog(modalId, closeId) {
    const modal = document.getElementById(modalId);
    const close = document.getElementById(closeId);
    if (!modal || !close) return;
    close.addEventListener('click', () => closeDialog(modal));
    // Close on backdrop click (click outside the dialog rect).
    modal.addEventListener('click', (e) => {
      const rect = modal.getBoundingClientRect();
      const inside = e.clientX >= rect.left && e.clientX <= rect.right &&
                     e.clientY >= rect.top  && e.clientY <= rect.bottom;
      if (!inside) closeDialog(modal);
    });
  }
  function wireModal() {
    wireDialog('pinModal',   'pinClose');
    wireDialog('storyModal', 'storyClose');
  }

  /* ---------- Hub buttons (toggle collapsible sections) ----------
     Each .hub__btn carries data-target with the id of the section it controls.
     At most ONE panel may be open at a time: clicking another button closes
     whichever panel is currently visible before opening the new one. */
  function wireHubButtons() {
    const buttons = Array.from(document.querySelectorAll('.hub__btn'));
    buttons.forEach((btn) => {
      btn.addEventListener('click', () => {
        const id = btn.dataset.target;
        const panel = document.getElementById(id);
        if (!panel) return;
        const willOpen = panel.hasAttribute('hidden');
        // Close every panel + reset every button.
        buttons.forEach((b) => {
          const p = document.getElementById(b.dataset.target);
          if (p) p.setAttribute('hidden', '');
          b.setAttribute('aria-expanded', 'false');
        });
        if (willOpen) {
          panel.removeAttribute('hidden');
          btn.setAttribute('aria-expanded', 'true');
          // Defer scroll so the layout settles after the panel becomes visible.
          requestAnimationFrame(() => {
            panel.scrollIntoView({ behavior: 'smooth', block: 'start' });
          });
        }
      });
    });
  }

  /* ---------- Map zoom dialog ----------
     Click anywhere on the map (except a pin) to open the full-resolution
     map in a fullscreen scrollable dialog. Pins keep their own behaviour. */
  function wireMapZoom() {
    const stage = document.getElementById('mapStage');
    const dialog = document.getElementById('mapZoom');
    const scroll = document.getElementById('mapZoomScroll');
    const img = document.getElementById('mapZoomImg');
    const close = document.getElementById('mapZoomClose');
    const sourceImg = document.getElementById('mapImage');
    if (!stage || !dialog || !img || !close || !scroll || !sourceImg) return;

    function openZoom() {
      // Lazy-set src on first open so the (cached) image loads on demand.
      if (!img.getAttribute('src')) img.src = sourceImg.currentSrc || sourceImg.src;
      if (typeof dialog.showModal === 'function') dialog.showModal();
      else dialog.setAttribute('open', '');
      // Center the image once it's laid out.
      requestAnimationFrame(() => {
        scroll.scrollLeft = (scroll.scrollWidth  - scroll.clientWidth)  / 2;
        scroll.scrollTop  = (scroll.scrollHeight - scroll.clientHeight) / 2;
      });
    }
    function closeZoom() {
      if (typeof dialog.close === 'function') dialog.close();
      else dialog.removeAttribute('open');
    }

    stage.addEventListener('click', (e) => {
      // Pins have their own click handler; don't open the zoom for them.
      if (e.target.closest('.cottage-hotspot')) return;
      // Wait until the map image is actually loaded.
      if (!stage.classList.contains('has-image')) return;
      openZoom();
    });

    close.addEventListener('click', closeZoom);
    // Click on backdrop area (the dialog itself, outside the scroll container)
    // closes the zoom.
    dialog.addEventListener('click', (e) => {
      if (e.target === dialog) closeZoom();
    });

    // Click-drag panning for desktop (touch already pans natively).
    let dragging = false;
    let startX = 0, startY = 0, startScrollX = 0, startScrollY = 0;
    scroll.addEventListener('pointerdown', (e) => {
      // Skip touch/pen — let the browser handle native scrolling/pinching.
      if (e.pointerType !== 'mouse') return;
      // Don't capture clicks that started on a pin — pointer capture would
      // re-route the pointerup to the scroll element and swallow the click.
      if (e.target.closest('.cottage-hotspot')) return;
      dragging = true;
      startX = e.clientX; startY = e.clientY;
      startScrollX = scroll.scrollLeft; startScrollY = scroll.scrollTop;
      scroll.classList.add('is-dragging');
      scroll.setPointerCapture(e.pointerId);
    });
    scroll.addEventListener('pointermove', (e) => {
      if (!dragging) return;
      scroll.scrollLeft = startScrollX - (e.clientX - startX);
      scroll.scrollTop  = startScrollY - (e.clientY - startY);
    });
    const endDrag = (e) => {
      if (!dragging) return;
      dragging = false;
      scroll.classList.remove('is-dragging');
      try { scroll.releasePointerCapture(e.pointerId); } catch (_) {}
    };
    scroll.addEventListener('pointerup', endDrag);
    scroll.addEventListener('pointercancel', endDrag);
  }

  /* ---------- Hero slideshow ----------
     Crossfades through the cottage photos stacked inside .hero__slides. The
     .is-active class controls opacity; only one slide is opaque at a time. */
  function wireHeroSlideshow() {
    const slides = document.querySelectorAll('.hero__slide');
    if (slides.length < 2) return;
    const SLIDE_MS = 5000;
    let i = 0;
    // Make sure exactly one slide starts active (defensive — markup already
    // sets it on the first one).
    slides.forEach((s, idx) => s.classList.toggle('is-active', idx === 0));
    setInterval(() => {
      slides[i].classList.remove('is-active');
      i = (i + 1) % slides.length;
      slides[i].classList.add('is-active');
    }, SLIDE_MS);
  }

  /* ---------- Trophies (Skarbiec) ----------
     Renders the union of (defined badges in BADGES) ∪ (earned badges in
     persist.data.badges) as cards inside #trophyGrid. Earned badges get
     full colour + the date; not-yet-earned defined badges show locked.
     Earned-but-undefined badges (a future definition arrived later? a
     console-awarded test?) still render so progress isn't hidden. The
     numeric pip on the floating button mirrors the earned count. */
  function renderTrophies() {
    const grid    = document.getElementById('trophyGrid');
    const empty   = document.getElementById('trophyEmpty');
    const toggle  = document.getElementById('trophiesOpen');
    const countEl = document.getElementById('trophiesCount');
    if (!grid || !empty || !toggle || !countEl) return;

    const earnedIds = persist.earnedBadges();
    const earnedSet = new Set(earnedIds);
    countEl.textContent = String(earnedIds.length);
    toggle.classList.toggle('trophies-toggle--has', earnedIds.length > 0);

    // Show every defined badge plus any earned ones we don't have a
    // definition for yet (preserves progress across registry edits).
    const ids = Array.from(new Set([...Object.keys(BADGES), ...earnedIds]));
    grid.replaceChildren();

    if (ids.length === 0) {
      empty.removeAttribute('hidden');
      grid.setAttribute('hidden', '');
      return;
    }
    empty.setAttribute('hidden', '');
    grid.removeAttribute('hidden');

    for (const id of ids) {
      const def = BADGES[id] || {};
      const meta = persist.data.badges[id];
      const isEarned = earnedSet.has(id);

      const li = document.createElement('li');
      li.className = 'trophy ' + (isEarned ? 'trophy--earned' : 'trophy--locked');
      li.dataset.badge = id;

      const art = document.createElement('div');
      art.className = 'trophy__art';
      if (def.image) {
        const img = document.createElement('img');
        img.src = def.image;
        img.alt = def.name || id;
        img.loading = 'lazy';
        img.decoding = 'async';
        art.appendChild(img);
      } else {
        art.textContent = isEarned ? '★' : '?';
      }

      const body = document.createElement('div');
      body.className = 'trophy__body';

      const h3 = document.createElement('h3');
      h3.className = 'trophy__name';
      h3.textContent = def.name || id;
      body.appendChild(h3);

      if (def.description) {
        const p = document.createElement('p');
        p.className = 'trophy__desc';
        p.textContent = def.description;
        body.appendChild(p);
      }

      if (isEarned && meta && meta.earnedAt) {
        const p = document.createElement('p');
        p.className = 'trophy__date';
        let when = meta.earnedAt;
        try {
          when = new Date(meta.earnedAt)
            .toLocaleDateString('pl-PL', { dateStyle: 'long' });
        } catch (_) {}
        p.innerHTML = `Zdobyto: <time datetime="${meta.earnedAt}">${escapeHtml(when)}</time>`;
        body.appendChild(p);
      }

      li.appendChild(art);
      li.appendChild(body);
      grid.appendChild(li);
    }
  }

  function wireTrophies() {
    const modal = document.getElementById('trophiesModal');
    const open  = document.getElementById('trophiesOpen');
    const close = document.getElementById('trophiesClose');
    if (!modal || !open || !close) return;
    open.addEventListener('click', () => {
      renderTrophies();   // refresh the grid each time the dialog opens
      showDialog(modal);
    });
    close.addEventListener('click', () => closeDialog(modal));
    modal.addEventListener('click', (e) => {
      const r = modal.getBoundingClientRect();
      const inside = e.clientX >= r.left && e.clientX <= r.right &&
                     e.clientY >= r.top  && e.clientY <= r.bottom;
      if (!inside) closeDialog(modal);
    });
  }

  /* ---------- 4-digit code form ---------- */
  function wireCodeForm() {
    const form = document.getElementById('codeForm');
    const input = document.getElementById('historiaKod');
    const out = document.getElementById('codeResult');
    form.addEventListener('submit', async (e) => {
      e.preventDefault();
      const v = (input.value || '').trim();
      if (!/^\d{4}$/.test(v)) {
        out.textContent = 'Podaj prawidłowy 4-cyfrowy kod znaleziony na tabliczce Chatynki.';
        return;
      }
      // crypto.subtle exists only in secure contexts (HTTPS or localhost).
      // Plain http:// over LAN (e.g. http://some-host:8000) lands here —
      // say so explicitly instead of a generic "try again".
      if (!window.isSecureContext || !window.crypto?.subtle) {
        out.textContent = `Sprawdzanie kodu wymaga bezpiecznego połączenia, a strona działa na „${location.origin}”. `
          + 'Otwórz ją przez HTTPS albo przez http://localhost.';
        return;
      }
      if (!state.codeHashes) {
        out.textContent = 'Nie udało się wczytać danych weryfikacji kodów — odśwież stronę i spróbuj ponownie.';
        return;
      }
      const c = await cottageByCode(v);
      if (!c) {
        out.textContent = 'Nieznany kod. Sprawdź tabliczkę na chatynce.';
        return;
      }
      const justFound = persist.markFound(c.slug, { code: v });
      // Repaint pins so the just-uncovered cottage shows in "found" colour
      // both on the inline map and in the zoom dialog. Also refresh the
      // trophies pip — future award rules (driven by foundSlugs.length,
      // for example) may have unlocked a badge.
      if (justFound) {
        drawCottages();
        renderTrophies();
        // Anonymous, aggregate counts (never tied to a visitor). Guarded so a
        // blocked/absent counter never throws. count.js URL-encodes the params
        // itself, so we pass raw strings (no manual encodeURIComponent).
        if (window.goatcounter && typeof window.goatcounter.count === 'function') {
          // Per-cottage breakdown: which cottages get discovered.
          window.goatcounter.count({
            path:  'found-' + c.slug,
            title: 'Cottage found: ' + c.title,
            event: true,
          });
          // Constant path — its total count = all cottage discoveries combined.
          window.goatcounter.count({
            path:  'cottage-found',
            title: 'Cottage found (any)',
            event: true,
          });
          // Progress distribution: how many cottages this visitor has found so
          // far (includes the one just uncovered). Hit counts on progress-1,
          // progress-2, … show how far seekers get — still anonymous, no
          // per-visitor identity. Bounded by the cottage count, so the path
          // set stays small.
          const foundCount = persist.foundSlugs().length;
          window.goatcounter.count({
            path:  'progress-' + foundCount,
            title: 'Reached ' + foundCount + ' found',
            event: true,
          });
        }
      }
      out.innerHTML = `✨ Magia ożywa… Elf z <strong>${c.title}</strong> chce Ci coś opowiedzieć.`;
      openStory(c);
    });
  }

  /* ---------- Boot ---------- */
  async function init() {
    persist.load();
    // Wire UI affordances first so toggles work even if data loading fails.
    wireHeroSlideshow();
    wireHubButtons();
    wireModal();
    wireCodeForm();
    wireMapZoom();
    wireAudioPlayer();
    wireTrophies();
    renderTrophies();   // initial paint of the count pip
    loadCodeHashes();   // independent of the map — failure only blocks code entry
    try {
      await loadCottages();
      drawCottages();
    } catch (err) {
      console.error('[Chatynkowo] init failed', err);
      const host = document.getElementById('mapHotspots');
      if (host) host.innerHTML =
        `<p style="padding:2rem;color:#f5e6b8;background:rgba(0,0,0,.6);">
           Nie udało się wczytać chatynek. Otwórz stronę przez serwer HTTP
           (np. <code>python3 -m http.server</code>).
         </p>`;
    }

    // Tourist route is independent of the cottage hotspots — load + render it
    // even if the map data above failed.
    await loadRoute();
    renderRoute();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
